def first_restaurant(restaurant_list, restaurant_string):
    l = restaurant_list.copy()
    l.insert(0, l.pop(l.index(restaurant_string)))
    return l
    

sales_restaurants = [
#     '100 Wardour Street',
    '14 Hills',
    '20 Stories', 
#     'Aster', 
#     'Avenue', 
    'Bluebird Chelsea', 
#     'Blueprint Café', 
    'Butlers Wharf Chophouse', 
    'Cantina', 
    "Coq d'Argent", 
    'East 59th', 
    'Fiume', 
    'German Gymnasium', 
    'Issho',
    'Klosterhaus',
#     'Launceston Place', 
    'Le Pont de la Tour', 
    'Madison', 
    'New Street Warehouse', 
    'Orrery', 
    'Paternoster Chophouse', 
    'Plateau', 
#     'Quaglinos', 
    'Radici', 
#     'Sartoria', 
    'Skylon', 
#     'South Place Hotel', 
    'Trinity', 
    'White City',
#     'The Modern Pantry',
]

bookings_restaurants = [
#     '100 Wardour St',
    '14 Hills',
    '20 Stories',
    'Angelica',
#     'Angler',
#     'Aster',
#     'Avenue',
    'Bluebird Chelsea',
    'Bluebird White City',
    'Butlers Wharf Chophouse',
    'Cantina del Ponte',
    "Coq d'Argent",
#     'Crafthouse',
    'East 59th',
    'Fish Market',
    'Fiume',
    'German Gymnasium',
    'Issho',
    'Klosterhaus',
#     'Launceston Place',
    'Madison',
    'New Street Grill',
    'Orrery',
    'Paternoster Chophouse',
    'Plateau',
    'Pont de la Tour',
#     "Quaglino's",
    'Radici',
#     'Sartoria',
    'Skylon',
#     'South Place Chop House',
#     'The Modern Pantry',
]

sales_to_bookings_restaurants_dict = {
    '100 Wardour Street': '100 Wardour St',
    '14 Hills': '14 Hills',
    '20 Stories': '20 Stories',
    'Aster': 'Aster',
    'Avenue': 'Avenue',
    'Bluebird Chelsea': 'Bluebird Chelsea Restaurant',
    'Blueprint Café': 'Blueprint Café',
    'Butlers Wharf Chophouse': 'Butlers Wharf Chophouse Restaurant',
    'Cantina': 'Cantina del Ponte',
    "Coq d'Argent": "Coq d'Argent",
    'East 59th': 'East 59th',
    'Fiume': 'Fiume',
    'German Gymnasium': 'German Gymnasium',
    'Issho': 'Issho Restaurant',
    'Klosterhaus': 'Klosterhaus',
    'Launceston Place': 'Launceston Place',
    'Le Pont de la Tour': 'Pont de la Tour',
    'Madison': 'Madison Restaurant',
    'New Street Warehouse': ['New Street Grill', 'Fish Market'],
    'Orrery': 'Orrery',
    'Paternoster Chophouse': 'Paternoster Chophouse',
    'Plateau': 'Plateau',
    'Quaglinos': "Quaglino's Restaurant",
    'Radici': 'Radici',
    'Sartoria': 'Sartoria',
    'Skylon': 'Skylon',
    'South Place Hotel': ['South Place Chop House','Angler Restaurant'],
    'Trinity': ['Angelica','Crafthouse'],
    'White City': 'Bluebird White City',
    'The Modern Pantry':'The Modern Pantry',
}

bookings_to_sales_restaurants_dict = {
    '100 Wardour St': '100 Wardour Street',
    '14 Hills': '14 Hills',
    '20 Stories': '20 Stories',
    'Angelica': 'Trinity',
    'Angler': 'South Place Hotel',
    'Aster': 'Aster',
    'Avenue': 'Avenue',
    'Bluebird Chelsea': 'Bluebird Chelsea',
    'Bluebird White City': 'White City',
    'Butlers Wharf Chophouse': 'Butlers Wharf Chophouse',
    'Cantina del Ponte': 'Cantina',
    "Coq d'Argent": "Coq d'Argent",
    'Crafthouse': 'Trinity',
    'East 59th': 'East 59th',
    'Fish Market': 'New Street Warehouse',
    'Fiume': 'Fiume',
    'German Gymnasium': 'German Gymnasium',
    'Issho': 'Issho',
    'Klosterhaus': 'Klosterhaus',
    'Launceston Place': 'Launceston Place',
    'Madison': 'Madison',
    'New Street Grill': 'New Street Warehouse',
    'Orrery': 'Orrery',
    'Paternoster Chophouse': 'Paternoster Chophouse',
    'Plateau': 'Plateau',
    'Pont de la Tour': 'Le Pont de la Tour',
    "Quaglino's": "Quaglinos",
    'Radici': 'Radici',
    'Sartoria': 'Sartoria',
    'Skylon': 'Skylon',
    'South Place Chop House': 'South Place Hotel',
    'The Modern Pantry': 'The Modern Pantry'
}

user_restaurants = {
    'dandd':{
        'sales' : sales_restaurants,
        'bookings' : bookings_restaurants,
    },
    'des@danddlondon.com':{
        'sales' : sales_restaurants,
        'bookings' : bookings_restaurants,
    },
    'davidloewi@danddlondon.com':{
        'sales' : sales_restaurants,
        'bookings' : bookings_restaurants,
    },
    'annabels@danddlondon.com':{
        'sales' : sales_restaurants,
        'bookings' : bookings_restaurants,
    },
    'marki@danddlondon.com':{
        'sales' : sales_restaurants,
        'bookings' : bookings_restaurants,
    },
    'lisaf@danddlondon.com':{
        'sales' : sales_restaurants,
        'bookings' : bookings_restaurants,
    },
    'benc@danddlondon.com':{
        'sales' : sales_restaurants,
        'bookings' : bookings_restaurants,
    },
    'jaspreetr@danddlondon.com':{
        'sales' : sales_restaurants,
        'bookings' : bookings_restaurants,
    },
    'carolc@danddlondon.com':{
        'sales' : sales_restaurants,
        'bookings' : bookings_restaurants,
    },
    'michael@danddlondon.com':{
        'sales':[
#             '100 Wardour Street',
            '14 Hills',
#             'Avenue',
            'Bluebird Chelsea',
            'Madison', 
#             'Quaglinos', 
            'Skylon', 
            'White City'
        ],
        'bookings':[
#             '100 Wardour St',
            '14 Hills',
#             'Avenue',
            'Bluebird Chelsea',
            'Bluebird White City',
            'Madison',
#             "Quaglino's",
            'Skylon'
        ],
    },
    'jb@danddlondon.com':{
        'sales':[
            '20 Stories', 
#             'Aster', 
            "Coq d'Argent", 
            'East 59th', 
            'German Gymnasium', 
            'Issho',
            'New Street Warehouse',
            'Paternoster Chophouse', 
            'Plateau', 
            'Trinity'
        ],
        'bookings':[
            '20 Stories',
            'Angelica',
#             'Aster',
            "Coq d'Argent",
#             'Crafthouse',
            'East 59th',
            'Fish Market',
            'German Gymnasium',
            'Issho',
            'Klosterhaus',
            'New Street Grill',
            'Orrery',
            'Paternoster Chophouse',
            'Plateau'
        ],
    },
    'sharonw@danddlondon.com':{
        'sales':[
            'Butlers Wharf Chophouse', 
            'Cantina', 
            'Fiume',
#             'Launceston Place',
            'Le Pont de la Tour', 
            'Orrery', 
            'Radici',
#             'Sartoria',
#             'The Modern Pantry',
        ],
        'bookings':[
            'Butlers Wharf Chophouse',
            'Cantina del Ponte',
            'Fiume',
#             'Launceston Place',
            'Orrery',
            'Pont de la Tour',
            'Radici',
#             'Sartoria',
#             'The Modern Pantry',
        ],
    },
    'kimst@danddlondon.com':{
#         'sales':first_restaurant(sales_restaurants,'100 Wardour Street'),
#         'bookings':first_restaurant(bookings_restaurants,'100 Wardour St'),
        'sales':sales_restaurants,
        'bookings':bookings_restaurants
    },
    'massimilianod@danddlondon.com':{
#         'sales':first_restaurant(sales_restaurants,'14 Hills'),
#         'bookings':first_restaurant(bookings_restaurants,'14 Hills'),
        'sales':sales_restaurants,
        'bookings':bookings_restaurants
    },
    'philipu@danddlondon.com':{
        'sales':first_restaurant(sales_restaurants,'20 Stories'),
        'bookings':first_restaurant(bookings_restaurants,'20 Stories'),
    },
    'radk@danddlondon.com':{
#         'sales':first_restaurant(sales_restaurants,'Aster'),
#         'bookings':first_restaurant(bookings_restaurants,'Aster'),
        'sales':sales_restaurants,
        'bookings':bookings_restaurants
    },
    'joseu@danddlondon.com':{
#         'sales':first_restaurant(sales_restaurants,'Avenue'),
#         'bookings':first_restaurant(bookings_restaurants,'Avenue'),
        'sales':sales_restaurants,
        'bookings':bookings_restaurants
    },
    'matthewm@danddlondon.com':{
        'sales':first_restaurant(sales_restaurants,'Bluebird Chelsea'),
        'bookings':first_restaurant(bookings_restaurants,'Bluebird Chelsea'),
    },
    'mattheol@danddlondon.com':{
        'sales':first_restaurant(sales_restaurants,'White City'),
        'bookings':first_restaurant(bookings_restaurants,'Bluebird White City'),
    },
    'imantsz@danddlondon.com':{
        'sales':first_restaurant(sales_restaurants,'Butlers Wharf Chophouse'),
        'bookings':first_restaurant(bookings_restaurants,'Butlers Wharf Chophouse'),
    },
    'ornetsf@danddlondon.com':{
        'sales':first_restaurant(sales_restaurants,'Cantina'),
        'bookings':first_restaurant(bookings_restaurants,'Cantina del Ponte'),
    },
    'seang@danddlondon.com':{
        'sales':first_restaurant(sales_restaurants,"Coq d'Argent"),
        'bookings':first_restaurant(bookings_restaurants,"Coq d'Argent"),
    },
    'jonathanpf@danddlondon.com':{
        'sales':first_restaurant(sales_restaurants,'East 59th'),
        'bookings':first_restaurant(bookings_restaurants,'East 59th'),
    },
    'micharb@danddlondon.com':{
        'sales':first_restaurant(sales_restaurants,'Fiume'),
        'bookings':first_restaurant(bookings_restaurants,'Fiume'),
    },
    'samb@danddlondon.com':{
        'sales':first_restaurant(sales_restaurants,'German Gymnasium'),
        'bookings':first_restaurant(bookings_restaurants,'German Gymnasium'),
    },
    'williamg@danddlondon.com':{
        'sales':first_restaurant(sales_restaurants,'Issho'),
        'bookings':first_restaurant(bookings_restaurants,'Issho'),
    },
    'tiagop@danddlondon.com':{
        'sales':first_restaurant(sales_restaurants,'Klosterhaus'),
        'bookings':first_restaurant(bookings_restaurants,'Klosterhaus'),
    },
    'carlos@danddlondon.com':{
#         'sales':first_restaurant(sales_restaurants,'Launceston Place'),
#         'bookings':first_restaurant(bookings_restaurants,'Launceston Place'),
        'sales':sales_restaurants,
        'bookings':bookings_restaurants
    },
    'medr@danddlondon.com':{
        'sales':first_restaurant(sales_restaurants,'Madison'),
        'bookings':first_restaurant(bookings_restaurants,'Madison'),
    },
    'fadiln@danddlondon.com':{
        'sales':first_restaurant(sales_restaurants,'Orrery'),
        'bookings':first_restaurant(bookings_restaurants,'Orrery'),
    },
    'hannahn@danddlondon.com':{
        'sales':first_restaurant(sales_restaurants,'Paternoster Chophouse'),
        'bookings':first_restaurant(bookings_restaurants,'Paternoster Chophouse'),
    },
    'alfonsoc@danddlondon.com':{
        'sales':first_restaurant(sales_restaurants,'Plateau'),
        'bookings':first_restaurant(bookings_restaurants,'Plateau'),
    },
    'olgag@danddlondon.com':{
        'sales':first_restaurant(sales_restaurants,'Le Pont de la Tour'),
        'bookings':first_restaurant(bookings_restaurants,'Pont de la Tour'),
    },
    'vidmantasg@danddlondon.com':{
#         'sales':first_restaurant(sales_restaurants,"Quaglino's"),
#         'bookings':first_restaurant(bookings_restaurants,"Quaglino's"),
        'sales':sales_restaurants,
        'bookings':bookings_restaurants
    },
    'vitoc@danddlondon.com':{
        'sales':first_restaurant(sales_restaurants,'Radici'),
        'bookings':first_restaurant(bookings_restaurants,'Radici'),
    },
    'encirobf@danddlondon.com':{
#         'sales':first_restaurant(sales_restaurants,'Sartoria'),
#         'bookings':first_restaurant(bookings_restaurants,'Sartoria'),
        'sales':sales_restaurants,
        'bookings':bookings_restaurants
    },
    'dainiusk@danddlondon.com':{
        'sales':first_restaurant(sales_restaurants,'Skylon'),
        'bookings':first_restaurant(bookings_restaurants,'Skylon'),
    },
    'nono@danddlondon.com':{
#         'sales':first_restaurant(sales_restaurants,'South Place Chop House'),
#         'bookings':first_restaurant(bookings_restaurants,'South Place Hotel'),
        'sales':sales_restaurants,
        'bookings':bookings_restaurants
    },
    'annap@danddlondon.com':{
#         'sales':first_restaurant(sales_restaurants,'The Modern Pantry'),
#         'bookings':first_restaurant(bookings_restaurants,'The Modern Pantry'),
        'sales':sales_restaurants,
        'bookings':bookings_restaurants
    },
}

restaurant_abbreviations = {'100WDST': {'sales': '100 Wardour Street', 'bookings': '100 Wardour St'},
 '14H': {'sales': '14 Hills', 'bookings': '14 Hills'},
 '20ST': {'sales': '20 Stories', 'bookings': '20 Stories'},
 'ANGEL': {'sales': 'Trinity', 'bookings': 'Angelica'},
 'ANGLER': {'sales': 'South Place Hotel', 'bookings': 'Angler'},
 'AST': {'sales': 'Aster', 'bookings': 'Aster'},
 'AVE': {'sales': 'Avenue', 'bookings': 'Avenue'},
 'BBCH': {'sales': 'Bluebird Chelsea', 'bookings': 'Bluebird Chelsea'},
 'BBCH CA': {'sales': 'Bluebird Chelsea', 'bookings': 'Bluebird Chelsea Café'},
 'BBCH PDR': {'sales': 'Bluebird Chelsea', 'bookings': 'Bluebird Chelsea PDR'},
 'BBWC': {'sales': 'White City', 'bookings': 'Bluebird White City'},
 'BWCH': {'sales': 'Butlers Wharf Chophouse',
  'bookings': 'Butlers Wharf Chophouse'},
 'CANT': {'sales': 'Cantina', 'bookings': 'Cantina del Ponte'},
 'COQ': {'sales': "Coq d'Argent", 'bookings': "Coq d'Argent"},
 'CRA': {'sales': 'Trinity', 'bookings': 'Crafthouse'},
 'E59': {'sales': 'East 59th', 'bookings': 'East 59th'},
 'F M': {'sales': 'New Street Warehouse', 'bookings': 'Fish Market'},
 'FIU': {'sales': 'Fiume', 'bookings': 'Fiume'},
 'GG': {'sales': 'German Gymnasium', 'bookings': 'German Gymnasium'},
 'ISSH': {'sales': 'Issho', 'bookings': 'Issho'},
 'KLO': {'sales': 'Klosterhaus', 'bookings': 'Klosterhaus'},
 'LP': {'sales': 'Launceston Place', 'bookings': 'Launceston Place'},
 'MAD': {'sales': 'Madison', 'bookings': 'Madison'},
 'NSG': {'sales': 'New Street Warehouse', 'bookings': 'New Street Grill'},
 'ORR': {'sales': 'Orrery', 'bookings': 'Orrery'},
 'PCH': {'sales': 'Paternoster Chophouse',
  'bookings': 'Paternoster Chophouse'},
 'PLA': {'sales': 'Plateau', 'bookings': 'Plateau'},
 'PDLT': {'sales': 'Le Pont de la Tour', 'bookings': 'Pont de la Tour'},
 'QUA': {'sales': 'Quaglinos', 'bookings': "Quaglino's"},
 'RAD': {'sales': 'Radici', 'bookings': 'Radici'},
 'SAR': {'sales': 'Sartoria', 'bookings': 'Sartoria'},
 'SKY': {'sales': 'Skylon', 'bookings': 'Skylon'},
 'SPCH': {'sales': 'South Place Hotel', 'bookings': 'South Place Chop House'},
 'BPC': {'sales': 'Blueprint Café', 'bookings': 'Blueprint Café'},
 'OBB': {'sales': 'New Street Warehouse', 'bookings': 'Old Bengal Bar'},
 'QUA BAR': {'sales': 'Quaglinos', 'bookings': "Quaglino's Bar"},
 'QUA PDR': {'sales': 'Quaglinos', 'bookings': "Quaglino's PDR"},
 'TMP': {'sales': 'The Modern Pantry', 'bookings': 'The Modern Pantry'},
 'TRI': {'sales': 'Trinity', 'bookings': ['Angelica', 'Crafthouse']},
 'SPH': {'sales': 'South Place Hotel',
  'bookings': ['Angler', 'South Place Chop House']},
 'REX': {'sales': 'Royal Exchange', 'bookings': 'Royal Exchange'},
 'NSW': {'sales': 'New Street Warehouse',
  'bookings': ['Fish Market', 'New Street Grill']},
 'KP': {'sales': 'Kensington Place', 'bookings': 'Kensington Place'},
 'FS': {'sales': 'Kensington Place', 'bookings': 'Fish Shop'},
 'A&B': {'sales': 'Alexander & Bjorck', 'bookings': 'Alexander & Bjorck'}}